//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convenience_Store_Entyti
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyalCustomerMostProduct
    {
        public string cID { get; set; }
        public string cName { get; set; }
        public Nullable<int> TotalProducts { get; set; }
    }
}
